export const ACTION_TYPES = {
	SET_TRENDING_TODAY: 'APP.SET_TRENDING_TODAY',
	SET_DATA_FOR: 'APP.SET_DATA_FOR',
	SET_FS_ID_GET_DETAILS: 'APP.SET_FS_ID_GET_DETAILS',
	SET_USER_DETAILS: 'APP.SET_USER_DETAILS',
	SET_USER_MOBILE: 'APP.SET_USER_MOBILE',
	SET_USER_CONTACTS_DICT: 'APP.SET_USER_CONTACTS_DICT',
	SET_COUNTRY_CODE: 'APP.SET_COUNTRY_CODE',
	SET_COUNTRY: 'APP.SET_COUNTRY'
};
